### ISSUE TITLE
Consider dual license w/Apache?

### ISSUE THREAD

**Issue by mmastrac** [Phundrak/output-vt100-rs#1]
I came across this cool crate while looking through the pretty_assertions and the recent changes to support Windows. One thing that might be an issue - the current GPL3 license - might be a surprise to some individuals who pull that crate in.

Would you consider dual or triple licensing with another license like Apache/MIT?

**Comment by nbouteme** [comment]
It makes sense to license it under a license that's compatible with the package it was originally designed to supplement.
I would re-license it under MIT, but I also need @Phundrak 's agreement, I don't think he would mind either, but I'd rather be safe.

**Comment by nbouteme** [comment]
It's now published under MIT.
