### ISSUE TITLE
Make a release with the README license fix?

### ISSUE THREAD

**Issue by llucax** [Phundrak/output-vt100-rs#3]
Commit https://github.com/Phundrak/output-vt100-rs/commit/e83cb168bd0e29214848852c95e191df0a983ec1 fixed a wrong ALT text for the license badge that said the project is under GPLv3, but this change was never released as a crate, so FOSSA is still picking this false positive.

It would be useful to make a release with the fix so the fix can actually be effective.

**Comment by Phundrak** [comment]
Good catch! I will try to make a new release in the upcoming hours.

--
Lucien “Phundrak” Cartier-Tilet
Étudiant en Master Informatique, Tuteur, Université Paris 8
https://phundrak.com (Français)
https://phundrak.com/en (English)

Sent from GNU/Emacs

**Comment by Phundrak** [comment]
Damn, I don’t know what happened, it seems I completely forgot about
this. Anyways, the update has been published, and I included in it a
quick style fix.

Lucien Cartier-Tilet ***@***.***> writes:

> Good catch! I will try to make a new release in the upcoming hours.


--
Lucien “Phundrak” Cartier-Tilet
<https://phundrak.com> (Français)
<https://phundrak.com/en> (English)
Sent from GNU/Emacs
